### ISSUE TITLE
brew install ssp-kernel-cq_frk_fm3

### ISSUE THREAD

**Issue by kaizen-nagoya** [PizzaFactory/homebrew-toppers_open#1]
==> Installing ssp-kernel-cq_frk_fm3 from pizzafactory/homebrew-toppers_open
==> Installing dependencies for ssp-kernel-cq_frk_fm3: toppers-ngk-cfg108, repo, gnupg
==> Installing ssp-kernel-cq_frk_fm3 dependency: toppers-ngk-cfg108
==> Downloading http://support.toppers-open.org/ngk_cfg/get/cfg-1.8.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/toppers-ngk-cfg108-1.8.0.tar.bz2
==> ./configure
==> make depend
==> make
clang++ -O2   -I/usr/local/include -I..  -c -o output_file.o output_file.cpp
clang++ -O2   -I/usr/local/include -I..  -c -o s_record.o s_record.cpp
clang++ -O2   -I/usr/local/include -I..  -c -o ucn_parser.o ucn_parser.cpp
ar rcs libitronx.a cfg1_out.o checker.o component.o factory.o preprocess.o static_api.o
ar rcs libtoppers.a builtin_function.o c_chlit_parser.o c_ident_parser.o c_int_parser.o c_keywords.o c_plus_plus_keywords.o c_strlit_parser.o cpp.o diagnostics.o gettext.o global.o io.o macro_processor.o mbchar_parser.o nm_symbol.o output_file.o s_record.o ucn_parser.o

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/pizzafactory/homebrew-toppers_open/issues

$ brew doctor
Your system is ready to brew.
 $ brew update
Already up-to-date.
rubyをawk, perlの代わりに使いはじめて3ヶ月。
他にも、いろいろ入れているのが邪魔をしているのか。何を調べればよいでしょうか。
OS X 10.10.2(16GB)

**Comment by monaka** [comment]
手元のOSX10.10.2 + 最新の brew ではビルドできました．
お手元のと私のとで clang のバージョンが異なる可能性が高いです．
私での出力は，下記のとおりです．

```
$ clang --version
Apple LLVM vesion 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

コマンドラインツールのインストール方法は，[このページなど](http://qiita.com/VoQn/items/0dc95f2adbace10bf31d)探すといくつか見つかります．

**Comment by monaka** [comment]
手元では動作しているので，won't fix で close します．
もしご不明点がありましたら，本チケットにコメントをください．
reopen を検討します．
